jwt:
    time: 90231321
    ret: hello-world123444
posco:
    name: 3기4444
    count: 2033333
test:
    datasource:
        url: jdbc:mysql://?.?.?.?:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
        username: rollin
        password: 1234
